import { Activity, AlertTriangle, Boxes, Braces, RadioReceiver, ShieldAlert } from "lucide-react";
import { EmptyState } from "../components/EmptyState";
import { HashValue } from "../components/HashValue";
import { ProvenanceLine } from "../components/ProvenanceLine";
import { SectionHeader } from "../components/SectionHeader";
import { StatusBadge } from "../components/StatusBadge";
import { formatDateTime } from "../data/format";
import type { DashboardData } from "../data/types";

function canaryCounts(data: DashboardData) {
  const swapSignals = data.memorySignals.filter((signal) => signal.signalType === "swap_memory_signal").length;
  return [
    {
      label: "Canary pulses",
      value: data.flowPulseObservations.length.toString(),
      detail: `${swapSignals} swap memory signal(s)`,
      status: "finalized" as const,
    },
    {
      label: "Rootfields",
      value: data.rootfields.length.toString(),
      detail: `${data.rootflowTransitions.length} Rootflow transitions`,
      status: "observed" as const,
    },
    {
      label: "Rejected logs",
      value: String(data.metadata.canary?.counts.rejectedLogs ?? 0),
      detail: "guarded reader result",
      status: (data.metadata.canary?.counts.rejectedLogs ?? 0) > 0 ? "failed" as const : "verified" as const,
    },
    {
      label: "Duplicates",
      value: String(data.metadata.canary?.counts.duplicates ?? 0),
      detail: "reader duplicate policy",
      status: (data.metadata.canary?.counts.duplicates ?? 0) > 0 ? "unresolved" as const : "verified" as const,
    },
    {
      label: "Source verified",
      value: "pending",
      detail: "automation ready; API key required",
      status: "unresolved" as const,
    },
  ];
}

export function CanaryDeploymentView({ data }: { data: DashboardData }) {
  const canary = data.metadata.canary;
  const counts = canaryCounts(data);
  const flowPulseContracts = canary?.contracts.filter((contract) => contract.emitsFlowPulse) ?? [];

  return (
    <div className="view-stack">
      <SectionHeader
        eyebrow="base mainnet canary"
        title="Live canary read"
        detail="Guarded Base mainnet read path for the deployed V0 FlowPulse surfaces. This view is for launch demos and operator review; it is not a production-readiness claim."
      />

      <section className="canary-hero" aria-label="Canary boundary">
        <div>
          <span className="eyebrow">guardrail</span>
          <h2>Visible on Base, still gated for production</h2>
          <p>
            The dashboard is reading committed canary artifacts generated by the Base mainnet canary reader.
            Verifier reports, source verification completion, multisig ownership, and real Uniswap v4 hook wiring
            remain separate launch gates.
          </p>
        </div>
        <div className="canary-read-window">
          <RadioReceiver size={18} aria-hidden="true" />
          <dl>
            <div>
              <dt>chain</dt>
              <dd>{data.chain.chainId}</dd>
            </div>
            <div>
              <dt>window</dt>
              <dd>
                {canary?.readWindow.fromBlock} - {canary?.readWindow.toBlock}
              </dd>
            </div>
            <div>
              <dt>captured</dt>
              <dd>{formatDateTime(data.metadata.generatedAt)}</dd>
            </div>
          </dl>
        </div>
      </section>

      <section className="metric-grid" aria-label="Canary metrics">
        {counts.map((metric) => (
          <article className="metric-tile" key={metric.label}>
            <span>{metric.label}</span>
            <strong>{metric.value}</strong>
            <div>
              <StatusBadge status={metric.status} compact />
              <small>{metric.detail}</small>
            </div>
          </article>
        ))}
      </section>

      <section className="overview-grid">
        <div className="panel panel-wide">
          <div className="panel-heading">
            <div>
              <Activity size={18} aria-hidden="true" />
              <h2>Canary FlowPulse stream</h2>
            </div>
            <span>{data.flowPulseObservations.length} observed</span>
          </div>
          {data.flowPulseObservations.length > 0 ? (
            <div className="record-list">
              {data.flowPulseObservations.map((observation) => (
                <article className="record-row" key={observation.observationId}>
                  <div>
                    <div className="record-title">
                      <StatusBadge status={observation.status} compact />
                      <HashValue value={observation.observationId} label="observation id" />
                    </div>
                    <p>{observation.summary}</p>
                    <ProvenanceLine provenance={observation.provenance} lastUpdated={observation.lastUpdated} />
                  </div>
                  <dl className="record-facts">
                    <div>
                      <dt>block</dt>
                      <dd>{observation.blockNumber}</dd>
                    </div>
                    <div>
                      <dt>type</dt>
                      <dd>{observation.pulseType}</dd>
                    </div>
                    <div>
                      <dt>tx</dt>
                      <dd>
                        <HashValue value={observation.txHash} trim="short" />
                      </dd>
                    </div>
                    <div>
                      <dt>log</dt>
                      <dd>{observation.logIndex}</dd>
                    </div>
                  </dl>
                </article>
              ))}
            </div>
          ) : (
            <EmptyState title="No canary observations" detail="Run the guarded Base canary reader and regenerate dashboard canary data." />
          )}
        </div>

        <div className="panel">
          <div className="panel-heading">
            <div>
              <Boxes size={18} aria-hidden="true" />
              <h2>FlowPulse contracts</h2>
            </div>
            <span>{flowPulseContracts.length} sources</span>
          </div>
          <div className="compact-list">
            {flowPulseContracts.map((contract) => (
              <article key={contract.address}>
                <StatusBadge status="observed" compact />
                <div>
                  <strong>{contract.name}</strong>
                  <small>
                    <HashValue value={contract.address} trim="short" />
                  </small>
                </div>
              </article>
            ))}
          </div>
        </div>

        <div className="panel">
          <div className="panel-heading">
            <div>
              <ShieldAlert size={18} aria-hidden="true" />
              <h2>Launch gates</h2>
            </div>
            <span>not production</span>
          </div>
          <div className="canary-boundaries">
            {(canary?.boundaries ?? []).map((boundary) => (
              <span key={boundary}>{boundary}</span>
            ))}
          </div>
        </div>

        <div className="panel panel-wide">
          <div className="panel-heading">
            <div>
              <Braces size={18} aria-hidden="true" />
              <h2>Canary Rootflow state</h2>
            </div>
            <span>{data.rootflowTransitions.length} transitions</span>
          </div>
          <div className="contract-event-list">
            {data.rootflowTransitions.map((transition) => (
              <article key={transition.transitionId}>
                <div>
                  <StatusBadge status={transition.status} compact />
                  <strong>
                    transition <HashValue value={transition.transitionId} trim="short" />
                  </strong>
                </div>
                <dl>
                  <div>
                    <dt>pulse</dt>
                    <dd>
                      <HashValue value={transition.pulseId} trim="short" />
                    </dd>
                  </div>
                  <div>
                    <dt>next root</dt>
                    <dd>
                      <HashValue value={transition.nextRoot} trim="short" />
                    </dd>
                  </div>
                  <div>
                    <dt>reason</dt>
                    <dd>{transition.reasonCodes.join(", ")}</dd>
                  </div>
                </dl>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="json-panel">
        <div className="json-panel-header">
          <Braces size={16} aria-hidden="true" />
          <span>{data.metadata.runtimeDataPath}</span>
          <strong>canary JSON</strong>
        </div>
        <pre>{JSON.stringify(data, null, 2)}</pre>
      </section>
    </div>
  );
}
