import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { FlowMemoryClient, type JsonValue } from "./client.ts";
import { redactJsonValue } from "./redact.ts";

interface DevPackReport {
  schema: "flowmemory.dev_pack_e2e_report.v0";
  generatedAt: string;
  status: "passed" | "blocked" | "failed";
  rpcUrl: string;
  checks: Record<string, boolean>;
  methodCount: number;
  publicReadyMethodCount: number;
  firstHeight: string | null;
  secondHeight: string | null;
  missingEnvNames: string[];
  reportPaths: Record<string, string>;
  noLiveBroadcast: boolean;
  envValuesPrinted: boolean;
  noSecrets: boolean;
}

function asRecord(value: JsonValue): Record<string, JsonValue> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return {};
  return value as Record<string, JsonValue>;
}

function asArray(value: JsonValue): JsonValue[] {
  return Array.isArray(value) ? value : [];
}

function stringValue(value: JsonValue): string | null {
  return typeof value === "string" || typeof value === "number" ? String(value) : null;
}

function numberValue(value: JsonValue): number {
  return typeof value === "number" ? value : Number.parseInt(String(value ?? "0"), 10);
}

function heightValue(status: Record<string, JsonValue>): bigint | null {
  const height = stringValue(status.currentBlock ?? status.blockHeight ?? status.latestHeight ?? status.height ?? null);
  if (height === null || !/^\d+$/.test(height)) return null;
  return BigInt(height);
}

function collectMissingEnvNames(value: JsonValue, names = new Set<string>()): string[] {
  if (Array.isArray(value)) {
    for (const entry of value) collectMissingEnvNames(entry, names);
  } else if (value !== null && typeof value === "object") {
    for (const [key, entry] of Object.entries(value)) {
      if (key === "missingEnvNames" || key === "missingProductionEnvNames") {
        for (const name of asArray(entry as JsonValue)) names.add(String(name));
      } else {
        collectMissingEnvNames(entry as JsonValue, names);
      }
    }
  }
  return [...names].sort();
}

function methodEntry(discovery: Record<string, JsonValue>, methodName: string): Record<string, JsonValue> | null {
  const methods = asArray(discovery.methods).map((method) => asRecord(method));
  return methods.find((method) => method.method === methodName) ?? null;
}

function accountIdFromBalance(row: Record<string, JsonValue>): string | null {
  return stringValue(row.walletAddress ?? null) ?? stringValue(asRecord(row.balance ?? {}).accountId ?? null);
}

function amountFromBalance(row: Record<string, JsonValue>): bigint {
  const amount = stringValue(row.amount ?? asRecord(row.balance ?? {}).units ?? "0") ?? "0";
  return /^\d+$/.test(amount) ? BigInt(amount) : 0n;
}

function sleep(ms: number) {
  return new Promise((resolveSleep) => setTimeout(resolveSleep, ms));
}

async function waitForHeightAdvance(client: FlowMemoryClient, firstStatus: Record<string, JsonValue>, timeoutMs: number): Promise<Record<string, JsonValue>> {
  const firstHeight = heightValue(firstStatus);
  if (firstHeight === null) return firstStatus;
  const deadline = Date.now() + timeoutMs;
  let latestStatus = firstStatus;
  while (Date.now() < deadline) {
    await sleep(1000);
    latestStatus = asRecord(await client.chainStatus());
    const latestHeight = heightValue(latestStatus);
    if (latestHeight !== null && latestHeight > firstHeight) return latestStatus;
  }
  return latestStatus;
}

function repoRoot() {
  return resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
}

function writeGeneratedReference(discovery: Record<string, JsonValue>, outputPath: string) {
  const methods = asArray(discovery.methods)
    .map((method) => asRecord(method))
    .sort((left, right) => String(left.method ?? "").localeCompare(String(right.method ?? "")));
  const lines = [
    "# FlowMemory RPC Reference",
    "",
    "Generated by `npm run public:test:cli` from live `rpc_discover` output.",
    "",
    `- RPC path: \`${String(discovery.rpcPath ?? "/rpc")}\``,
    `- Chain id: \`${String(discovery.chainId ?? "unknown")}\``,
    `- Deployment mode: \`${String(discovery.deploymentMode ?? "unknown")}\``,
    `- Completion gate passed: \`${String(discovery.productionReady ?? false)}\``,
    `- Public RPC gate passed: \`${String(discovery.publicRpcReady ?? false)}\``,
    "",
    "| Method | Category | Mode | Public eligible |",
    "| --- | --- | --- | --- |",
    ...methods.map((method) => {
      return `| \`${String(method.method ?? "")}\` | ${String(method.category ?? "")} | ${String(method.mode ?? "")} | ${String(method.publicRpcEligible ?? false)} |`;
    }),
    "",
    "Public exposure still depends on the public deployment contract and owner inputs. This reference is not a public-ready claim.",
    "",
  ];
  writeFileSync(outputPath, lines.join("\n"), "utf8");
}

function writeMarkdownReport(report: DevPackReport, outputPath: string) {
  const passed = Object.entries(report.checks).filter(([, ok]) => ok).length;
  const total = Object.keys(report.checks).length;
  const lines = [
    "# FlowMemory Developer Pack E2E",
    "",
    `Status: \`${report.status}\``,
    "",
    `Generated at: \`${report.generatedAt}\``,
    `Checks: \`${passed}/${total}\``,
    `Method count: \`${report.methodCount}\``,
    `Public-ready method count: \`${report.publicReadyMethodCount}\``,
    `Height: \`${report.firstHeight ?? "unknown"} -> ${report.secondHeight ?? "unknown"}\``,
    "",
    "## Remaining Live Inputs",
    "",
    ...(report.missingEnvNames.length > 0 ? report.missingEnvNames.map((name) => `- \`${name}\``) : ["- None reported"]),
    "",
    "## Reports",
    "",
    ...Object.entries(report.reportPaths).map(([name, path]) => `- ${name}: \`${path}\``),
    "",
  ];
  writeFileSync(outputPath, lines.join("\n"), "utf8");
}

async function main() {
  const root = repoRoot();
  const rpcUrl = process.env.FLOWMEMORY_RPC_URL ?? "http://127.0.0.1:8787/rpc";
  const runDir = resolve(root, "docs", "agent-runs", "live-product-dev-pack");
  const sdkDocsDir = resolve(root, "docs", "sdk");
  mkdirSync(runDir, { recursive: true });
  mkdirSync(sdkDocsDir, { recursive: true });

  const client = new FlowMemoryClient({ rpcUrl, timeoutMs: 15000 });
  const discovery = asRecord(await client.rpcDiscover());
  const readiness = asRecord(await client.rpcReadiness());
  const health = asRecord(await client.health());
  const nodeStatus = asRecord(await client.nodeStatus());
  const firstStatus = asRecord(await client.chainStatus());
  const secondStatus = await waitForHeightAdvance(client, firstStatus, 30000);
  const blocks = asRecord(await client.blockList({ limit: 1 }));
  const firstBlock = asRecord(asArray(blocks.blocks)[0] ?? null);
  const blockDetail = asRecord(await client.blockGet({ blockNumber: stringValue(firstBlock.blockNumber) ?? stringValue(firstStatus.currentBlock) ?? "0" }));
  const transactions = asRecord(await client.transactionList({ limit: 1 }));
  const firstTransaction = asRecord(asArray(transactions.transactions)[0] ?? null);
  const transactionDetail = Object.keys(firstTransaction).length > 0
    ? asRecord(await client.transactionGet({ txId: stringValue(firstTransaction.transactionId) ?? stringValue(firstTransaction.txHash) ?? "" }))
    : {};
  const mempool = asRecord(await client.mempoolList({ limit: 1 }));
  const accounts = asRecord(await client.accountList({ limit: 5 }));
  const firstAccount = asRecord(asArray(accounts.accounts)[0] ?? null);
  const balance = asRecord(await client.balanceGet({ accountId: stringValue(firstAccount.accountId) ?? "" }));
  const walletMetadata = asRecord(await client.walletMetadataList({ limit: 5 }));
  const walletBalances = asRecord(await client.walletBalances({ limit: 1 }));
  const walletTransfers = asRecord(await client.walletTransfers({ limit: 1 }));
  const faucetEvents = asRecord(await client.faucetEventList({ limit: 1 }));
  const finality = asRecord(await client.finalityList({ limit: 1 }));
  const bridgeDeposits = asRecord(await client.bridgeDepositList({ limit: 1 }));
  const bridgeCredits = asRecord(await client.bridgeCreditList({ limit: 1 }));
  const withdrawals = asRecord(await client.withdrawalList({ limit: 1 }));
  const sendCandidateBalances = asRecord(await client.walletBalances({ limit: 25 }));
  const balanceRows = asArray(sendCandidateBalances.balances).map((row) => asRecord(row));
  const sender = balanceRows.find((row) => accountIdFromBalance(row) !== null && amountFromBalance(row) > 1n);
  const recipient = balanceRows.find((row) => accountIdFromBalance(row) !== null && accountIdFromBalance(row) !== accountIdFromBalance(sender ?? {}));
  if (sender === undefined || recipient === undefined) {
    throw new Error("dev-pack e2e could not find two local wallet accounts with a spendable balance");
  }
  const walletSend = asRecord(await client.walletSend({
    fromAccountId: accountIdFromBalance(sender) ?? "",
    toAccountId: accountIdFromBalance(recipient) ?? "",
    amountUnits: "1",
    memo: `flowmemory-dev-pack-e2e-${Date.now()}`,
    applyBlock: true,
    createRecipient: true,
  }));

  const cliPath = resolve(root, "services", "flowmemory-sdk", "src", "cli.ts");
  const cliStatusText = execFileSync(process.execPath, [cliPath, "status", "--json", "--rpc", rpcUrl], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
  });
  const cliStatus = JSON.parse(cliStatusText) as JsonValue;
  const cliBlocksText = execFileSync(process.execPath, [cliPath, "blocks", "--json", "--limit", "1", "--rpc", rpcUrl], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
  });
  const cliBlocks = JSON.parse(cliBlocksText) as JsonValue;
  const nodeExamplePath = resolve(root, "examples", "flowchain-node-quickstart.mjs");
  const nodeExampleText = execFileSync(process.execPath, [nodeExamplePath, "--send"], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
    env: { ...process.env, FLOWMEMORY_RPC_URL: rpcUrl },
  });
  const nodeExample = JSON.parse(nodeExampleText) as JsonValue;
  const browserExamplePath = resolve(root, "examples", "flowchain-browser-readiness", "index.html");
  const browserExampleText = existsSync(browserExamplePath) ? readFileSync(browserExamplePath, "utf8") : "";
  const requiredDocs = [
    "docs/developer/FLOWCHAIN_QUICKSTART.md",
    "docs/developer/FLOWCHAIN_WALLET_INTEGRATION.md",
    "docs/developer/FLOWCHAIN_BRIDGE_INTEGRATION.md",
    "docs/developer/FLOWCHAIN_NODE_OPERATOR.md",
    "docs/developer/FLOWCHAIN_APP_BUILDER.md",
    "docs/developer/FLOWCHAIN_EXPLORER_INDEXER.md",
    "docs/developer/FLOWCHAIN_FAUCET_TESTER_FUNDS.md",
    "docs/developer/FLOWCHAIN_RELEASE_COMPATIBILITY.md",
    "docs/developer/FLOWCHAIN_TROUBLESHOOTING.md",
    "docs/sdk/FLOWCHAIN_SDK.md",
    "docs/sdk/RPC_REFERENCE.generated.md",
  ];
  const missingDocs = requiredDocs.filter((docPath) => !existsSync(resolve(root, docPath)));

  const firstHeight = stringValue(firstStatus.currentBlock ?? firstStatus.blockHeight ?? firstStatus.latestHeight ?? firstStatus.height ?? null);
  const secondHeight = stringValue(secondStatus.currentBlock ?? secondStatus.blockHeight ?? secondStatus.latestHeight ?? secondStatus.height ?? null);
  const missingEnvNames = collectMissingEnvNames(readiness);
  const transactionSubmit = methodEntry(discovery, "transaction_submit");
  const devnetState = methodEntry(discovery, "devnet_state");
  const walletTransferHistory = methodEntry(discovery, "wallet_transfer_history");

  const referencePath = resolve(sdkDocsDir, "RPC_REFERENCE.generated.md");
  const reportPath = resolve(runDir, "dev-pack-e2e-report.json");
  const markdownPath = resolve(runDir, "DEV_PACK.md");
  const handoffPath = resolve(runDir, "HANDOFF.md");
  writeGeneratedReference(discovery, referencePath);

  const checks = {
    discoveryLoaded: String(discovery.schema ?? "") === "flowchain.rpc.discovery.v0",
    readinessLoaded: String(readiness.schema ?? "") === "flowchain.rpc.readiness.v0",
    healthReadable: String(health.schema ?? "") === "flowmemory.control_plane.health.v0",
    nodeStatusReadable: String(nodeStatus.schema ?? "") === "flowmemory.control_plane.node_status.v0",
    blockListReadable: String(blocks.schema ?? "") === "flowmemory.control_plane.block_list.v0",
    blockGetReadable: String(blockDetail.schema ?? "") === "flowmemory.control_plane.block_detail.v0",
    transactionListReadable: String(transactions.schema ?? "") === "flowmemory.control_plane.transaction_list.v0",
    transactionGetReadable: Object.keys(transactionDetail).length === 0 || String(transactionDetail.schema ?? "") === "flowmemory.control_plane.transaction_detail.v0",
    mempoolReadable: String(mempool.schema ?? "") === "flowmemory.control_plane.mempool_list.v0",
    accountListReadable: String(accounts.schema ?? "") === "flowmemory.control_plane.account_list.v0",
    balanceReadable: String(balance.schema ?? "") === "flowmemory.control_plane.balance.v0",
    walletMetadataReadable: String(walletMetadata.schema ?? "") === "flowmemory.control_plane.wallet_public_metadata_list.v0",
    walletTransfersReadable: String(walletTransfers.schema ?? "") === "flowmemory.control_plane.wallet_transfer_history.v0",
    walletBalancesReadable: String(walletBalances.schema ?? "") === "flowmemory.control_plane.wallet_balance_list.v0",
    faucetEventsReadable: String(faucetEvents.schema ?? "") === "flowmemory.control_plane.faucet_event_list.v0",
    finalityReadable: String(finality.schema ?? "") === "flowmemory.control_plane.finality_list.v0",
    bridgeLifecycleReadable: String(bridgeDeposits.schema ?? "") === "flowmemory.control_plane.bridge_deposit_list.v0"
      && String(bridgeCredits.schema ?? "") === "flowmemory.control_plane.bridge_credit_list.v0"
      && String(withdrawals.schema ?? "") === "flowmemory.control_plane.withdrawal_list.v0",
    walletSendRuntimeBacked: String(walletSend.schema ?? "") === "flowmemory.control_plane.wallet_send_result.v0",
    cliJsonStatus: String(asRecord(cliStatus).schema ?? "") === "flowmemory.control_plane.chain_status.v0",
    cliJsonBlocks: String(asRecord(cliBlocks).schema ?? "") === "flowmemory.control_plane.block_list.v0",
    nodeExamplePassed: String(asRecord(nodeExample).schema ?? "") === "flowchain.example.node_quickstart.v0" && asRecord(nodeExample).status === "passed",
    browserExamplePresent: browserExampleText.includes("/rpc/discover") && browserExampleText.includes("/rpc/readiness"),
    developerGuidesPresent: missingDocs.length === 0,
    heightAdvanced: firstHeight !== null && secondHeight !== null && BigInt(secondHeight) > BigInt(firstHeight),
    publicReadinessFailClosed: readiness.publicRpcReady === false && readiness.productionReady === false,
    publicWriteMethodsBlockedFromPublicList: transactionSubmit?.publicRpcEligible === false && walletTransferHistory?.publicRpcEligible === true,
    broadLocalStateBlockedFromPublicList: devnetState?.publicRpcEligible === false,
  };
  const status = Object.values(checks).every(Boolean) ? "passed" : "failed";
  const report: DevPackReport = {
    schema: "flowmemory.dev_pack_e2e_report.v0",
    generatedAt: new Date().toISOString(),
    status,
    rpcUrl,
    checks,
    methodCount: numberValue(discovery.methodCount ?? 0),
    publicReadyMethodCount: numberValue(discovery.publicReadyMethodCount ?? 0),
    firstHeight,
    secondHeight,
    missingEnvNames,
    reportPaths: {
      json: reportPath,
      markdown: markdownPath,
      handoff: handoffPath,
      rpcReference: referencePath,
    },
    noLiveBroadcast: true,
    envValuesPrinted: false,
    noSecrets: true,
  };

  writeFileSync(reportPath, JSON.stringify(redactJsonValue(report as unknown as JsonValue), null, 2), "utf8");
  writeMarkdownReport(report, markdownPath);
  writeFileSync(
    handoffPath,
    [
      "# FlowChain Developer Pack Handoff",
      "",
      `Status: \`${report.status}\``,
      "",
      "Implemented in this slice:",
      "",
      "- Private FlowChain SDK/devkit package under `services/flowmemory-sdk`.",
      "- Typed JSON-RPC client over the real FlowChain `/rpc` surface.",
      "- CLI commands for discovery, readiness, status, wallet balances, wallet transfers, bridge readiness, bridge status, and diagnostics.",
      "- CLI commands for blocks, transactions, mempool, accounts, balances, wallet metadata, faucet events, finality, bridge deposits, bridge credits, and withdrawals.",
      "- Node.js SDK example under `examples/flowchain-node-quickstart.mjs` and browser readiness example under `examples/flowchain-browser-readiness/`.",
      "- Developer guides for wallet integration, bridge integration, node operations, app building, explorer/indexer use, faucet/tester funds, release compatibility, and troubleshooting.",
      "- Generated RPC reference from live `rpc_discover`.",
      "- Dev-pack E2E report proving local RPC attachment, height reads, explorer reads, wallet reads, bridge lifecycle reads, runtime-backed local wallet sends, CLI JSON output, sample example execution, and public readiness fail-closed behavior.",
      "",
      "Remaining buildout:",
      "",
      "- Add signed transaction envelope examples once wallet signing boundaries are finalized for SDK use.",
      "- Promote the browser example to a packaged Vite/React app if the dashboard app is split into a reusable external starter.",
      "- Keep public/live readiness blocked until owner inputs and public deployment gates pass.",
      "",
      `Report: \`${reportPath}\``,
      "",
    ].join("\n"),
    "utf8",
  );

  console.log(`FlowChain dev-pack E2E status: ${report.status}`);
  console.log(`Report: ${reportPath}`);
  if (report.status !== "passed") process.exitCode = 1;
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
