import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { FlowChainClient, type JsonValue } from "./client.ts";
import { redactJsonValue } from "./redact.ts";

interface DevPackReport {
  schema: "flowchain.dev_pack_e2e_report.v0";
  generatedAt: string;
  status: "passed" | "blocked" | "failed";
  rpcUrl: string;
  checks: Record<string, boolean>;
  methodCount: number;
  publicReadyMethodCount: number;
  firstHeight: string | null;
  secondHeight: string | null;
  missingEnvNames: string[];
  reportPaths: Record<string, string>;
  noLiveBroadcast: boolean;
  envValuesPrinted: boolean;
  noSecrets: boolean;
}

function asRecord(value: JsonValue): Record<string, JsonValue> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return {};
  return value as Record<string, JsonValue>;
}

function asArray(value: JsonValue): JsonValue[] {
  return Array.isArray(value) ? value : [];
}

function stringValue(value: JsonValue): string | null {
  return typeof value === "string" || typeof value === "number" ? String(value) : null;
}

function numberValue(value: JsonValue): number {
  return typeof value === "number" ? value : Number.parseInt(String(value ?? "0"), 10);
}

function collectMissingEnvNames(value: JsonValue, names = new Set<string>()): string[] {
  if (Array.isArray(value)) {
    for (const entry of value) collectMissingEnvNames(entry, names);
  } else if (value !== null && typeof value === "object") {
    for (const [key, entry] of Object.entries(value)) {
      if (key === "missingEnvNames" || key === "missingProductionEnvNames") {
        for (const name of asArray(entry as JsonValue)) names.add(String(name));
      } else {
        collectMissingEnvNames(entry as JsonValue, names);
      }
    }
  }
  return [...names].sort();
}

function methodEntry(discovery: Record<string, JsonValue>, methodName: string): Record<string, JsonValue> | null {
  const methods = asArray(discovery.methods).map((method) => asRecord(method));
  return methods.find((method) => method.method === methodName) ?? null;
}

function accountIdFromBalance(row: Record<string, JsonValue>): string | null {
  return stringValue(row.walletAddress ?? null) ?? stringValue(asRecord(row.balance ?? {}).accountId ?? null);
}

function amountFromBalance(row: Record<string, JsonValue>): bigint {
  const amount = stringValue(row.amount ?? asRecord(row.balance ?? {}).units ?? "0") ?? "0";
  return /^\d+$/.test(amount) ? BigInt(amount) : 0n;
}

function sleep(ms: number) {
  return new Promise((resolveSleep) => setTimeout(resolveSleep, ms));
}

function repoRoot() {
  return resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
}

function writeGeneratedReference(discovery: Record<string, JsonValue>, outputPath: string) {
  const methods = asArray(discovery.methods)
    .map((method) => asRecord(method))
    .sort((left, right) => String(left.method ?? "").localeCompare(String(right.method ?? "")));
  const lines = [
    "# FlowChain RPC Reference",
    "",
    "Generated by `npm run flowchain:dev-pack:e2e` from live `rpc_discover` output.",
    "",
    `- RPC path: \`${String(discovery.rpcPath ?? "/rpc")}\``,
    `- Chain id: \`${String(discovery.chainId ?? "unknown")}\``,
    `- Deployment mode: \`${String(discovery.deploymentMode ?? "unknown")}\``,
    `- Completion gate passed: \`${String(discovery.productionReady ?? false)}\``,
    `- Public RPC gate passed: \`${String(discovery.publicRpcReady ?? false)}\``,
    "",
    "| Method | Category | Mode | Public eligible |",
    "| --- | --- | --- | --- |",
    ...methods.map((method) => {
      return `| \`${String(method.method ?? "")}\` | ${String(method.category ?? "")} | ${String(method.mode ?? "")} | ${String(method.publicRpcEligible ?? false)} |`;
    }),
    "",
    "Public exposure still depends on the public deployment contract and owner inputs. This reference is not a public-ready claim.",
    "",
  ];
  writeFileSync(outputPath, lines.join("\n"), "utf8");
}

function writeMarkdownReport(report: DevPackReport, outputPath: string) {
  const passed = Object.entries(report.checks).filter(([, ok]) => ok).length;
  const total = Object.keys(report.checks).length;
  const lines = [
    "# FlowChain Developer Pack E2E",
    "",
    `Status: \`${report.status}\``,
    "",
    `Generated at: \`${report.generatedAt}\``,
    `Checks: \`${passed}/${total}\``,
    `Method count: \`${report.methodCount}\``,
    `Public-ready method count: \`${report.publicReadyMethodCount}\``,
    `Height: \`${report.firstHeight ?? "unknown"} -> ${report.secondHeight ?? "unknown"}\``,
    "",
    "## Remaining Live Inputs",
    "",
    ...(report.missingEnvNames.length > 0 ? report.missingEnvNames.map((name) => `- \`${name}\``) : ["- None reported"]),
    "",
    "## Reports",
    "",
    ...Object.entries(report.reportPaths).map(([name, path]) => `- ${name}: \`${path}\``),
    "",
  ];
  writeFileSync(outputPath, lines.join("\n"), "utf8");
}

async function main() {
  const root = repoRoot();
  const rpcUrl = process.env.FLOWCHAIN_RPC_URL ?? "http://127.0.0.1:8787/rpc";
  const runDir = resolve(root, "docs", "agent-runs", "live-product-dev-pack");
  const sdkDocsDir = resolve(root, "docs", "sdk");
  mkdirSync(runDir, { recursive: true });
  mkdirSync(sdkDocsDir, { recursive: true });

  const client = new FlowChainClient({ rpcUrl, timeoutMs: 15000 });
  const discovery = asRecord(await client.rpcDiscover());
  const readiness = asRecord(await client.rpcReadiness());
  const firstStatus = asRecord(await client.chainStatus());
  await sleep(2500);
  const secondStatus = asRecord(await client.chainStatus());
  const walletBalances = asRecord(await client.walletBalances({ limit: 1 }));
  const walletTransfers = asRecord(await client.walletTransfers({ limit: 1 }));
  const sendCandidateBalances = asRecord(await client.walletBalances({ limit: 25 }));
  const balanceRows = asArray(sendCandidateBalances.balances).map((row) => asRecord(row));
  const sender = balanceRows.find((row) => accountIdFromBalance(row) !== null && amountFromBalance(row) > 1n);
  const recipient = balanceRows.find((row) => accountIdFromBalance(row) !== null && accountIdFromBalance(row) !== accountIdFromBalance(sender ?? {}));
  if (sender === undefined || recipient === undefined) {
    throw new Error("dev-pack e2e could not find two local wallet accounts with a spendable balance");
  }
  const walletSend = asRecord(await client.walletSend({
    fromAccountId: accountIdFromBalance(sender) ?? "",
    toAccountId: accountIdFromBalance(recipient) ?? "",
    amountUnits: "1",
    memo: `flowchain-dev-pack-e2e-${Date.now()}`,
    applyBlock: true,
    createRecipient: true,
  }));

  const cliPath = resolve(root, "services", "flowchain-sdk", "src", "cli.ts");
  const cliStatusText = execFileSync(process.execPath, [cliPath, "status", "--json", "--rpc", rpcUrl], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
  });
  const cliStatus = JSON.parse(cliStatusText) as JsonValue;

  const firstHeight = stringValue(firstStatus.currentBlock ?? firstStatus.blockHeight ?? null);
  const secondHeight = stringValue(secondStatus.currentBlock ?? secondStatus.blockHeight ?? null);
  const missingEnvNames = collectMissingEnvNames(readiness);
  const transactionSubmit = methodEntry(discovery, "transaction_submit");
  const walletTransferHistory = methodEntry(discovery, "wallet_transfer_history");

  const referencePath = resolve(sdkDocsDir, "RPC_REFERENCE.generated.md");
  const reportPath = resolve(runDir, "dev-pack-e2e-report.json");
  const markdownPath = resolve(runDir, "DEV_PACK.md");
  const handoffPath = resolve(runDir, "HANDOFF.md");
  writeGeneratedReference(discovery, referencePath);

  const checks = {
    discoveryLoaded: String(discovery.schema ?? "") === "flowchain.rpc.discovery.v0",
    readinessLoaded: String(readiness.schema ?? "") === "flowchain.rpc.readiness.v0",
    walletTransfersReadable: String(walletTransfers.schema ?? "") === "flowmemory.control_plane.wallet_transfer_history.v0",
    walletBalancesReadable: String(walletBalances.schema ?? "") === "flowmemory.control_plane.wallet_balance_list.v0",
    walletSendRuntimeBacked: String(walletSend.schema ?? "") === "flowmemory.control_plane.wallet_send_result.v0",
    cliJsonStatus: String(asRecord(cliStatus).schema ?? "") === "flowmemory.control_plane.chain_status.v0",
    heightAdvanced: firstHeight !== null && secondHeight !== null && BigInt(secondHeight) > BigInt(firstHeight),
    publicReadinessFailClosed: readiness.publicRpcReady === false && readiness.productionReady === false,
    publicWriteMethodsBlockedFromPublicList: transactionSubmit?.publicRpcEligible === false && walletTransferHistory?.publicRpcEligible === true,
  };
  const status = Object.values(checks).every(Boolean) ? "passed" : "failed";
  const report: DevPackReport = {
    schema: "flowchain.dev_pack_e2e_report.v0",
    generatedAt: new Date().toISOString(),
    status,
    rpcUrl: "http://127.0.0.1:8787/rpc",
    checks,
    methodCount: numberValue(discovery.methodCount ?? 0),
    publicReadyMethodCount: numberValue(discovery.publicReadyMethodCount ?? 0),
    firstHeight,
    secondHeight,
    missingEnvNames,
    reportPaths: {
      json: reportPath,
      markdown: markdownPath,
      handoff: handoffPath,
      rpcReference: referencePath,
    },
    noLiveBroadcast: true,
    envValuesPrinted: false,
    noSecrets: true,
  };

  writeFileSync(reportPath, JSON.stringify(redactJsonValue(report as unknown as JsonValue), null, 2), "utf8");
  writeMarkdownReport(report, markdownPath);
  writeFileSync(
    handoffPath,
    [
      "# FlowChain Developer Pack Handoff",
      "",
      `Status: \`${report.status}\``,
      "",
      "Implemented in this slice:",
      "",
      "- Private FlowChain SDK/devkit package under `services/flowchain-sdk`.",
      "- Typed JSON-RPC client over the real FlowChain `/rpc` surface.",
      "- CLI commands for discovery, readiness, status, wallet balances, wallet transfers, bridge readiness, bridge status, and diagnostics.",
      "- Generated RPC reference from live `rpc_discover`.",
      "- Dev-pack E2E report proving local RPC attachment, height reads, wallet balance reads, wallet transfer reads, a runtime-backed local wallet send, CLI JSON output, and public readiness fail-closed behavior.",
      "",
      "Remaining buildout:",
      "",
      "- Add signed transaction envelope examples once wallet signing boundaries are finalized for SDK use.",
      "- Add browser/Vite sample app.",
      "- Expand docs into full wallet, bridge, node operator, explorer, faucet, release, and troubleshooting guides.",
      "- Keep public/live readiness blocked until owner inputs and public deployment gates pass.",
      "",
      `Report: \`${reportPath}\``,
      "",
    ].join("\n"),
    "utf8",
  );

  console.log(`FlowChain dev-pack E2E status: ${report.status}`);
  console.log(`Report: ${reportPath}`);
  if (report.status !== "passed") process.exitCode = 1;
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
