import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { FlowChainClient, type JsonValue } from "./client.ts";
import { redactJsonValue } from "./redact.ts";

interface DevPackReport {
  schema: "flowchain.dev_pack_e2e_report.v0";
  generatedAt: string;
  status: "passed" | "blocked" | "failed";
  rpcUrl: string;
  checks: Record<string, boolean>;
  methodCount: number;
  publicReadyMethodCount: number;
  firstHeight: string | null;
  secondHeight: string | null;
  missingEnvNames: string[];
  reportPaths: Record<string, string>;
  noLiveBroadcast: boolean;
  envValuesPrinted: boolean;
  noSecrets: boolean;
}

function asRecord(value: JsonValue): Record<string, JsonValue> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return {};
  return value as Record<string, JsonValue>;
}

function asArray(value: JsonValue): JsonValue[] {
  return Array.isArray(value) ? value : [];
}

function stringValue(value: JsonValue): string | null {
  return typeof value === "string" || typeof value === "number" ? String(value) : null;
}

function numberValue(value: JsonValue): number {
  return typeof value === "number" ? value : Number.parseInt(String(value ?? "0"), 10);
}

function heightValue(status: Record<string, JsonValue>): bigint | null {
  const height = stringValue(status.currentBlock ?? status.blockHeight ?? status.latestHeight ?? status.height ?? null);
  if (height === null || !/^\d+$/.test(height)) return null;
  return BigInt(height);
}

function collectMissingEnvNames(value: JsonValue, names = new Set<string>()): string[] {
  if (Array.isArray(value)) {
    for (const entry of value) collectMissingEnvNames(entry, names);
  } else if (value !== null && typeof value === "object") {
    for (const [key, entry] of Object.entries(value)) {
      if (key === "missingEnvNames" || key === "missingProductionEnvNames") {
        for (const name of asArray(entry as JsonValue)) names.add(String(name));
      } else {
        collectMissingEnvNames(entry as JsonValue, names);
      }
    }
  }
  return [...names].sort();
}

function methodEntry(discovery: Record<string, JsonValue>, methodName: string): Record<string, JsonValue> | null {
  const methods = asArray(discovery.methods).map((method) => asRecord(method));
  return methods.find((method) => method.method === methodName) ?? null;
}

function accountIdFromBalance(row: Record<string, JsonValue>): string | null {
  return stringValue(row.walletAddress ?? null) ?? stringValue(asRecord(row.balance ?? {}).accountId ?? null);
}

function amountFromBalance(row: Record<string, JsonValue>): bigint {
  const amount = stringValue(row.amount ?? asRecord(row.balance ?? {}).units ?? "0") ?? "0";
  return /^\d+$/.test(amount) ? BigInt(amount) : 0n;
}

function sleep(ms: number) {
  return new Promise((resolveSleep) => setTimeout(resolveSleep, ms));
}

async function waitForHeightAdvance(client: FlowChainClient, firstStatus: Record<string, JsonValue>, timeoutMs: number): Promise<Record<string, JsonValue>> {
  const firstHeight = heightValue(firstStatus);
  if (firstHeight === null) return firstStatus;
  const deadline = Date.now() + timeoutMs;
  let latestStatus = firstStatus;
  while (Date.now() < deadline) {
    await sleep(1000);
    latestStatus = asRecord(await client.chainStatus());
    const latestHeight = heightValue(latestStatus);
    if (latestHeight !== null && latestHeight > firstHeight) return latestStatus;
  }
  return latestStatus;
}

function repoRoot() {
  return resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
}

function writeGeneratedReference(discovery: Record<string, JsonValue>, outputPath: string) {
  const methods = asArray(discovery.methods)
    .map((method) => asRecord(method))
    .sort((left, right) => String(left.method ?? "").localeCompare(String(right.method ?? "")));
  const lines = [
    "# FlowChain RPC Reference",
    "",
    "Generated by `npm run flowchain:dev-pack:e2e` from live `rpc_discover` output.",
    "",
    `- RPC path: \`${String(discovery.rpcPath ?? "/rpc")}\``,
    `- Chain id: \`${String(discovery.chainId ?? "unknown")}\``,
    `- Deployment mode: \`${String(discovery.deploymentMode ?? "unknown")}\``,
    `- Completion gate passed: \`${String(discovery.productionReady ?? false)}\``,
    `- Public RPC gate passed: \`${String(discovery.publicRpcReady ?? false)}\``,
    "",
    "| Method | Category | Mode | Public eligible |",
    "| --- | --- | --- | --- |",
    ...methods.map((method) => {
      return `| \`${String(method.method ?? "")}\` | ${String(method.category ?? "")} | ${String(method.mode ?? "")} | ${String(method.publicRpcEligible ?? false)} |`;
    }),
    "",
    "Public exposure still depends on the public deployment contract and owner inputs. This reference is not a public-ready claim.",
    "",
  ];
  writeFileSync(outputPath, lines.join("\n"), "utf8");
}

function writeMarkdownReport(report: DevPackReport, outputPath: string) {
  const passed = Object.entries(report.checks).filter(([, ok]) => ok).length;
  const total = Object.keys(report.checks).length;
  const lines = [
    "# FlowChain Developer Pack E2E",
    "",
    `Status: \`${report.status}\``,
    "",
    `Generated at: \`${report.generatedAt}\``,
    `Checks: \`${passed}/${total}\``,
    `Method count: \`${report.methodCount}\``,
    `Public-ready method count: \`${report.publicReadyMethodCount}\``,
    `Height: \`${report.firstHeight ?? "unknown"} -> ${report.secondHeight ?? "unknown"}\``,
    "",
    "## Remaining Live Inputs",
    "",
    ...(report.missingEnvNames.length > 0 ? report.missingEnvNames.map((name) => `- \`${name}\``) : ["- None reported"]),
    "",
    "## Reports",
    "",
    ...Object.entries(report.reportPaths).map(([name, path]) => `- ${name}: \`${path}\``),
    "",
  ];
  writeFileSync(outputPath, lines.join("\n"), "utf8");
}

function writeInventoryReport(args: {
  outputPath: string;
  checks: Record<string, boolean>;
  missingDocs: string[];
  missingEnvNames: string[];
  methodCount: number;
  publicReadyMethodCount: number;
}) {
  const implementedIf = (ok: boolean) => ok ? "implemented" : "partial";
  const docsStatus = args.missingDocs.length === 0 ? "implemented" : "partial";
  const publicStatus = args.publicReadyMethodCount > 0 ? "implemented" : "blocked-owner-input";
  const bridgeStatus = args.missingEnvNames.some((name) => name.startsWith("FLOWCHAIN_BASE8453_") || name.startsWith("FLOWCHAIN_PILOT_"))
    ? "blocked-owner-input"
    : "implemented";
  const rpcStatus = args.missingEnvNames.some((name) => name.startsWith("FLOWCHAIN_RPC_")) ? "blocked-owner-input" : "implemented";
  const inventory = [
    {
      surface: "SDK package",
      status: implementedIf(args.checks.discoveryLoaded && args.checks.readinessLoaded),
      evidence: "`services/flowchain-sdk` client calls live `/rpc` discovery and readiness.",
    },
    {
      surface: "CLI/devkit",
      status: implementedIf(args.checks.cliJsonStatus && args.checks.cliJsonBlocks && args.checks.cliJsonWaitTransaction),
      evidence: "CLI emits JSON for status, blocks, and transaction-inclusion waits.",
    },
    {
      surface: "RPC reference",
      status: implementedIf(args.methodCount > 0),
      evidence: `Generated from live discovery with ${args.methodCount} methods.`,
    },
    {
      surface: "Wallet reads and local send",
      status: implementedIf(args.checks.walletBalancesReadable && args.checks.walletTransfersReadable && args.checks.walletSendRuntimeBacked),
      evidence: "Reads balances/history and submits a runtime-backed local wallet transfer.",
    },
    {
      surface: "Signed transaction envelope",
      status: implementedIf(args.checks.signedEnvelopeExamplePassed && args.checks.cliSignedTransactionSubmit),
      evidence: "Example and CLI submit crypto-verified signed envelopes through `transaction_submit`.",
    },
    {
      surface: "Node.js example",
      status: implementedIf(args.checks.nodeExamplePassed),
      evidence: "`examples/flowchain-node-quickstart.mjs --send` runs against the local RPC.",
    },
    {
      surface: "Browser readiness example",
      status: args.checks.browserExamplePresent ? "partial" : "missing",
      evidence: "Static browser readiness example exists; external starter packaging is still future work.",
    },
    {
      surface: "Developer docs",
      status: docsStatus,
      evidence: args.missingDocs.length === 0 ? "Required wallet, bridge, operator, app, explorer, faucet, compatibility, and troubleshooting docs exist." : `Missing docs: ${args.missingDocs.join(", ")}.`,
    },
    {
      surface: "Explorer/indexer reads",
      status: implementedIf(args.checks.blockListReadable && args.checks.transactionListReadable && args.checks.accountListReadable),
      evidence: "SDK reads blocks, transactions, accounts, balances, mempool, finality, and faucet events.",
    },
    {
      surface: "Local bridge lifecycle reads",
      status: implementedIf(args.checks.bridgeLifecycleReadable),
      evidence: "SDK reads bridge deposits, credits, and withdrawals from the control-plane RPC.",
    },
    {
      surface: "Base 8453 live bridge pilot",
      status: bridgeStatus,
      evidence: bridgeStatus === "implemented" ? "Owner Base 8453 inputs are present." : "Live bridge stays fail-closed until owner Base 8453 and pilot inputs exist.",
    },
    {
      surface: "Public RPC read-only exposure",
      status: publicStatus,
      evidence: publicStatus === "implemented" ? "Discovery exposes public-ready methods." : "Public exposure stays fail-closed until owner public RPC edge inputs pass.",
    },
    {
      surface: "State backup live path",
      status: rpcStatus,
      evidence: rpcStatus === "implemented" ? "Owner public RPC and backup inputs are present." : "Live backup path remains blocked on owner RPC backup env.",
    },
    {
      surface: "Additional language SDKs",
      status: "missing",
      evidence: "The current dev pack supports the first TypeScript/Node SDK only.",
    },
  ];
  const lines = [
    "# FlowChain Developer Ecosystem Inventory",
    "",
    "Generated by `npm run flowchain:dev-pack:e2e`.",
    "",
    "| Surface | Classification | Evidence |",
    "| --- | --- | --- |",
    ...inventory.map((item) => `| ${item.surface} | ${item.status} | ${item.evidence} |`),
    "",
    "Classification values: `implemented`, `partial`, `fixture-only`, `blocked-owner-input`, `missing`.",
    "",
  ];
  writeFileSync(args.outputPath, lines.join("\n"), "utf8");
}

async function main() {
  const root = repoRoot();
  const rpcUrl = process.env.FLOWCHAIN_RPC_URL ?? "http://127.0.0.1:8787/rpc";
  const runDir = resolve(root, "docs", "agent-runs", "live-product-dev-pack");
  const sdkDocsDir = resolve(root, "docs", "sdk");
  mkdirSync(runDir, { recursive: true });
  mkdirSync(sdkDocsDir, { recursive: true });

  const client = new FlowChainClient({ rpcUrl, timeoutMs: 60000 });
  const discovery = asRecord(await client.rpcDiscover());
  const readiness = asRecord(await client.rpcReadiness());
  const health = asRecord(await client.health());
  const nodeStatus = asRecord(await client.nodeStatus());
  const firstStatus = asRecord(await client.chainStatus());
  const secondStatus = await waitForHeightAdvance(client, firstStatus, 30000);
  const blocks = asRecord(await client.blockList({ limit: 1 }));
  const firstBlock = asRecord(asArray(blocks.blocks)[0] ?? null);
  const blockDetail = asRecord(await client.blockGet({ blockNumber: stringValue(firstBlock.blockNumber) ?? stringValue(firstStatus.currentBlock) ?? "0" }));
  const transactions = asRecord(await client.transactionList({ limit: 1 }));
  const firstTransaction = asRecord(asArray(transactions.transactions)[0] ?? null);
  const transactionDetail = Object.keys(firstTransaction).length > 0
    ? asRecord(await client.transactionGet({ txId: stringValue(firstTransaction.transactionId) ?? stringValue(firstTransaction.txHash) ?? "" }))
    : {};
  const mempool = asRecord(await client.mempoolList({ limit: 1 }));
  const accounts = asRecord(await client.accountList({ limit: 5 }));
  const firstAccount = asRecord(asArray(accounts.accounts)[0] ?? null);
  const balance = asRecord(await client.balanceGet({ accountId: stringValue(firstAccount.accountId) ?? "" }));
  const walletMetadata = asRecord(await client.walletMetadataList({ limit: 5 }));
  const walletBalances = asRecord(await client.walletBalances({ limit: 1 }));
  const walletTransfers = asRecord(await client.walletTransfers({ limit: 1 }));
  const faucetEvents = asRecord(await client.faucetEventList({ limit: 1 }));
  const finality = asRecord(await client.finalityList({ limit: 1 }));
  const bridgeDeposits = asRecord(await client.bridgeDepositList({ limit: 1 }));
  const bridgeCredits = asRecord(await client.bridgeCreditList({ limit: 1 }));
  const withdrawals = asRecord(await client.withdrawalList({ limit: 1 }));
  const sendCandidateBalances = asRecord(await client.walletBalances({ limit: 25 }));
  const balanceRows = asArray(sendCandidateBalances.balances).map((row) => asRecord(row));
  const sender = balanceRows.find((row) => accountIdFromBalance(row) !== null && amountFromBalance(row) > 1n);
  const recipient = balanceRows.find((row) => accountIdFromBalance(row) !== null && accountIdFromBalance(row) !== accountIdFromBalance(sender ?? {}));
  if (sender === undefined || recipient === undefined) {
    throw new Error("dev-pack e2e could not find two local wallet accounts with a spendable balance");
  }
  const walletSend = asRecord(await client.walletSend({
    fromAccountId: accountIdFromBalance(sender) ?? "",
    toAccountId: accountIdFromBalance(recipient) ?? "",
    amountUnits: "1",
    memo: `flowchain-dev-pack-e2e-${Date.now()}`,
    applyBlock: true,
    createRecipient: true,
  }));
  const walletSendTxId = stringValue(walletSend.transferId) ?? stringValue(asArray(walletSend.txIds)[0] ?? null);
  const waitedTransaction = walletSendTxId === null
    ? {}
    : asRecord(await client.waitForTransaction({ txId: walletSendTxId, timeoutMs: 15000, pollMs: 500 }));

  const cliPath = resolve(root, "services", "flowchain-sdk", "src", "cli.ts");
  const cliStatusText = execFileSync(process.execPath, [cliPath, "status", "--json", "--rpc", rpcUrl], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
  });
  const cliStatus = JSON.parse(cliStatusText) as JsonValue;
  const cliBlocksText = execFileSync(process.execPath, [cliPath, "blocks", "--json", "--limit", "1", "--rpc", rpcUrl], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
  });
  const cliBlocks = JSON.parse(cliBlocksText) as JsonValue;
  const cliWaitTransaction = walletSendTxId === null
    ? {}
    : JSON.parse(execFileSync(process.execPath, [cliPath, "wait-transaction", "--json", "--tx", walletSendTxId, "--seconds", "15", "--poll-ms", "500", "--rpc", rpcUrl], {
        cwd: root,
        encoding: "utf8",
        windowsHide: true,
      })) as JsonValue;
  const nodeExamplePath = resolve(root, "examples", "flowchain-node-quickstart.mjs");
  const nodeExampleText = execFileSync(process.execPath, [nodeExamplePath, "--send"], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
    env: { ...process.env, FLOWCHAIN_RPC_URL: rpcUrl },
  });
  const nodeExample = JSON.parse(nodeExampleText) as JsonValue;
  const signedEnvelopeExamplePath = resolve(root, "examples", "flowchain-signed-envelope.mjs");
  const signedEnvelopeExampleText = execFileSync(process.execPath, [signedEnvelopeExamplePath, "--submit"], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
    env: { ...process.env, FLOWCHAIN_RPC_URL: rpcUrl },
  });
  const signedEnvelopeExample = JSON.parse(signedEnvelopeExampleText) as JsonValue;
  const cliSignedEnvelopePath = resolve(root, "devnet", "local", "flowchain-signed-envelope-example", "dev-pack-cli-signed-envelope.json");
  const cliSignedEnvelopePreparedText = execFileSync(process.execPath, [signedEnvelopeExamplePath, "--no-submit", "--write", cliSignedEnvelopePath], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
    env: { ...process.env, FLOWCHAIN_RPC_URL: rpcUrl },
  });
  const cliSignedEnvelopePrepared = JSON.parse(cliSignedEnvelopePreparedText) as JsonValue;
  const cliSignedSubmitText = execFileSync(process.execPath, [
    cliPath,
    "submit-signed-transaction",
    "--json",
    "--signed-envelope",
    cliSignedEnvelopePath,
    "--submitted-by",
    "flowchain-dev-pack-cli",
    "--runtime-submit-mode",
    "off",
    "--rpc",
    rpcUrl,
  ], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
  });
  const cliSignedSubmit = JSON.parse(cliSignedSubmitText) as JsonValue;
  const browserExamplePath = resolve(root, "examples", "flowchain-browser-readiness", "index.html");
  const browserExampleText = existsSync(browserExamplePath) ? readFileSync(browserExamplePath, "utf8") : "";
  const requiredDocs = [
    "docs/developer/FLOWCHAIN_QUICKSTART.md",
    "docs/developer/FLOWCHAIN_WALLET_INTEGRATION.md",
    "docs/developer/FLOWCHAIN_BRIDGE_INTEGRATION.md",
    "docs/developer/FLOWCHAIN_NODE_OPERATOR.md",
    "docs/developer/FLOWCHAIN_APP_BUILDER.md",
    "docs/developer/FLOWCHAIN_EXPLORER_INDEXER.md",
    "docs/developer/FLOWCHAIN_FAUCET_TESTER_FUNDS.md",
    "docs/developer/FLOWCHAIN_RELEASE_COMPATIBILITY.md",
    "docs/developer/FLOWCHAIN_TROUBLESHOOTING.md",
    "docs/sdk/FLOWCHAIN_SDK.md",
    "docs/sdk/RPC_REFERENCE.generated.md",
  ];
  const missingDocs = requiredDocs.filter((docPath) => !existsSync(resolve(root, docPath)));

  const firstHeight = stringValue(firstStatus.currentBlock ?? firstStatus.blockHeight ?? firstStatus.latestHeight ?? firstStatus.height ?? null);
  const secondHeight = stringValue(secondStatus.currentBlock ?? secondStatus.blockHeight ?? secondStatus.latestHeight ?? secondStatus.height ?? null);
  const missingEnvNames = collectMissingEnvNames(readiness);
  const transactionSubmit = methodEntry(discovery, "transaction_submit");
  const devnetState = methodEntry(discovery, "devnet_state");
  const walletTransferHistory = methodEntry(discovery, "wallet_transfer_history");

  const referencePath = resolve(sdkDocsDir, "RPC_REFERENCE.generated.md");
  const reportPath = resolve(runDir, "dev-pack-e2e-report.json");
  const markdownPath = resolve(runDir, "DEV_PACK.md");
  const handoffPath = resolve(runDir, "HANDOFF.md");
  const inventoryPath = resolve(runDir, "INVENTORY.md");
  writeGeneratedReference(discovery, referencePath);

  const baseChecks = {
    discoveryLoaded: String(discovery.schema ?? "") === "flowchain.rpc.discovery.v0",
    readinessLoaded: String(readiness.schema ?? "") === "flowchain.rpc.readiness.v0",
    healthReadable: String(health.schema ?? "") === "flowmemory.control_plane.health.v0",
    nodeStatusReadable: String(nodeStatus.schema ?? "") === "flowmemory.control_plane.node_status.v0",
    blockListReadable: String(blocks.schema ?? "") === "flowmemory.control_plane.block_list.v0",
    blockGetReadable: String(blockDetail.schema ?? "") === "flowmemory.control_plane.block_detail.v0",
    transactionListReadable: String(transactions.schema ?? "") === "flowmemory.control_plane.transaction_list.v0",
    transactionGetReadable: Object.keys(transactionDetail).length === 0 || String(transactionDetail.schema ?? "") === "flowmemory.control_plane.transaction_detail.v0",
    mempoolReadable: String(mempool.schema ?? "") === "flowmemory.control_plane.mempool_list.v0",
    accountListReadable: String(accounts.schema ?? "") === "flowmemory.control_plane.account_list.v0",
    balanceReadable: String(balance.schema ?? "") === "flowmemory.control_plane.balance.v0",
    walletMetadataReadable: String(walletMetadata.schema ?? "") === "flowmemory.control_plane.wallet_public_metadata_list.v0",
    walletTransfersReadable: String(walletTransfers.schema ?? "") === "flowmemory.control_plane.wallet_transfer_history.v0",
    walletBalancesReadable: String(walletBalances.schema ?? "") === "flowmemory.control_plane.wallet_balance_list.v0",
    faucetEventsReadable: String(faucetEvents.schema ?? "") === "flowmemory.control_plane.faucet_event_list.v0",
    finalityReadable: String(finality.schema ?? "") === "flowmemory.control_plane.finality_list.v0",
    bridgeLifecycleReadable: String(bridgeDeposits.schema ?? "") === "flowmemory.control_plane.bridge_deposit_list.v0"
      && String(bridgeCredits.schema ?? "") === "flowmemory.control_plane.bridge_credit_list.v0"
      && String(withdrawals.schema ?? "") === "flowmemory.control_plane.withdrawal_list.v0",
    walletSendRuntimeBacked: String(walletSend.schema ?? "") === "flowmemory.control_plane.wallet_send_result.v0",
    waitTransactionSdkIncluded: walletSendTxId !== null && waitedTransaction.status === "included",
    cliJsonStatus: String(asRecord(cliStatus).schema ?? "") === "flowmemory.control_plane.chain_status.v0",
    cliJsonBlocks: String(asRecord(cliBlocks).schema ?? "") === "flowmemory.control_plane.block_list.v0",
    cliJsonWaitTransaction: String(asRecord(cliWaitTransaction).schema ?? "") === "flowchain.sdk.wait_transaction.v0" && asRecord(cliWaitTransaction).status === "included",
    nodeExamplePassed: String(asRecord(nodeExample).schema ?? "") === "flowchain.example.node_quickstart.v0" && asRecord(nodeExample).status === "passed",
    signedEnvelopeExamplePassed: String(asRecord(signedEnvelopeExample).schema ?? "") === "flowchain.example.signed_envelope.v0"
      && asRecord(signedEnvelopeExample).status === "passed"
      && asRecord(signedEnvelopeExample).submitAccepted === true
      && asRecord(signedEnvelopeExample).submitStatus === "accepted_crypto_verified",
    cliSignedEnvelopePrepared: String(asRecord(cliSignedEnvelopePrepared).schema ?? "") === "flowchain.example.signed_envelope.v0"
      && asRecord(cliSignedEnvelopePrepared).status === "passed"
      && asRecord(cliSignedEnvelopePrepared).submitted === false
      && typeof asRecord(cliSignedEnvelopePrepared).writtenPath === "string",
    cliSignedTransactionSubmit: String(asRecord(cliSignedSubmit).schema ?? "") === "flowmemory.control_plane.transaction_submit_result.v0"
      && asRecord(cliSignedSubmit).accepted === true
      && asRecord(cliSignedSubmit).status === "accepted_crypto_verified",
    browserExamplePresent: browserExampleText.includes("/rpc/discover") && browserExampleText.includes("/rpc/readiness"),
    developerGuidesPresent: missingDocs.length === 0,
    heightAdvanced: firstHeight !== null && secondHeight !== null && BigInt(secondHeight) > BigInt(firstHeight),
    publicReadinessFailClosed: readiness.publicRpcReady === false && readiness.productionReady === false,
    publicWriteMethodsBlockedFromPublicList: transactionSubmit?.publicRpcEligible === false && walletTransferHistory?.publicRpcEligible === true,
    broadLocalStateBlockedFromPublicList: devnetState?.publicRpcEligible === false,
  };

  writeInventoryReport({
    outputPath: inventoryPath,
    checks: baseChecks,
    missingDocs,
    missingEnvNames,
    methodCount: numberValue(discovery.methodCount ?? 0),
    publicReadyMethodCount: numberValue(discovery.publicReadyMethodCount ?? 0),
  });
  const inventoryText = existsSync(inventoryPath) ? readFileSync(inventoryPath, "utf8") : "";
  const checks = {
    ...baseChecks,
    inventoryGenerated: inventoryText.includes("| SDK package | implemented |")
      && inventoryText.includes("blocked-owner-input")
      && inventoryText.includes("| Additional language SDKs | missing |"),
    inventorySafe: !/(privateKey|private_key|seed phrase|mnemonic|apiKey|webhook|BEGIN RSA PRIVATE KEY|BEGIN OPENSSH PRIVATE KEY)/i.test(inventoryText),
  };
  const status = Object.values(checks).every(Boolean) ? "passed" : "failed";
  const report: DevPackReport = {
    schema: "flowchain.dev_pack_e2e_report.v0",
    generatedAt: new Date().toISOString(),
    status,
    rpcUrl,
    checks,
    methodCount: numberValue(discovery.methodCount ?? 0),
    publicReadyMethodCount: numberValue(discovery.publicReadyMethodCount ?? 0),
    firstHeight,
    secondHeight,
    missingEnvNames,
    reportPaths: {
      json: reportPath,
      markdown: markdownPath,
      handoff: handoffPath,
      inventory: inventoryPath,
      rpcReference: referencePath,
    },
    noLiveBroadcast: true,
    envValuesPrinted: false,
    noSecrets: true,
  };

  writeFileSync(reportPath, JSON.stringify(redactJsonValue(report as unknown as JsonValue), null, 2), "utf8");
  writeMarkdownReport(report, markdownPath);
  writeFileSync(
    handoffPath,
    [
      "# FlowChain Developer Pack Handoff",
      "",
      `Status: \`${report.status}\``,
      "",
      "Implemented in this slice:",
      "",
      "- Private FlowChain SDK/devkit package under `services/flowchain-sdk`.",
      "- Typed JSON-RPC client over the real FlowChain `/rpc` surface.",
      "- CLI commands for discovery, readiness, status, wallet balances, wallet transfers, bridge readiness, bridge status, and diagnostics.",
      "- CLI commands for blocks, transactions, mempool, accounts, balances, wallet metadata, faucet events, finality, bridge deposits, bridge credits, and withdrawals.",
      "- SDK and CLI transaction-inclusion wait helpers backed by `transaction_get` polling.",
      "- SDK and CLI signed transaction envelope submission backed by the crypto-verified `transaction_submit` RPC.",
      "- Node.js SDK example under `examples/flowchain-node-quickstart.mjs` and browser readiness example under `examples/flowchain-browser-readiness/`.",
      "- Signed envelope example under `examples/flowchain-signed-envelope.mjs` that creates local wallets in memory, signs a FlowChain product transfer envelope, submits it to local cryptographic intake, and can write a CLI-ready envelope file.",
      "- Developer guides for wallet integration, bridge integration, node operations, app building, explorer/indexer use, faucet/tester funds, release compatibility, and troubleshooting.",
      "- Generated RPC reference from live `rpc_discover`.",
      "- Developer ecosystem inventory classifying implemented, partial, blocked, and missing surfaces.",
      "- Dev-pack E2E report proving local RPC attachment, height reads, explorer reads, wallet reads, bridge lifecycle reads, runtime-backed local wallet sends, signed-envelope intake, CLI JSON output, sample example execution, and public readiness fail-closed behavior.",
      "",
      "Remaining buildout:",
      "",
      "- Promote the browser example to a packaged Vite/React app if the dashboard app is split into a reusable external starter.",
      "- Keep public/live readiness blocked until owner inputs and public deployment gates pass.",
      "",
      `Report: \`${reportPath}\``,
      "",
    ].join("\n"),
    "utf8",
  );

  console.log(`FlowChain dev-pack E2E status: ${report.status}`);
  console.log(`Report: ${reportPath}`);
  if (report.status !== "passed") process.exitCode = 1;
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
